# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPost',
            fields=[
                ('uuid', models.UUIDField(editable=False,
                                          primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
