# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geopost', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoPost',
        ),
    ]
